<?php
/**
 * @file
 */

include_once('humanitarianresponse_locations.features.inc');

function humanitarianresponse_locations_load_by_pcode($pcode) {
  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'taxonomy_term')
    ->entityCondition('bundle', 'locations')
    ->fieldCondition('field_location_pcode', 'value', $pcode, '=')
    ->execute();
  if (!empty($result['taxonomy_term'])) {
    $tids = array_keys($result['taxonomy_term']);
    $tid = $tids[0];
    return taxonomy_term_load($tid);
  }
  else {
    return NULL;
  }
    
}


function humanitarianresponse_locations_hxl_synchronize($pcode) {
  if (module_exists('hxl_api')) {
    _humanitarianresponse_locations_hxl_synchronize_by_admin_level($pcode, 0);
    _humanitarianresponse_locations_hxl_synchronize_by_admin_level($pcode, 1);
    _humanitarianresponse_locations_hxl_synchronize_by_admin_level($pcode, 2);
  }
}

function _humanitarianresponse_locations_hxl_synchronize_by_admin_level($pcode, $level) {
  if (module_exists('hxl_api')) {
    $locations = hxl_api_get_locations_by_admin_level($pcode, $level);
    foreach ($locations as $location) {
      $term = humanitarianresponse_locations_load_by_pcode($location['pcode']);
      if (!isset($term)) {
        $voc = taxonomy_vocabulary_machine_name_load('locations');
        $term = new stdClass();
        $term->vid = $voc->vid;
      }
      $term->name = $location['name'];
      $term->field_location_pcode[LANGUAGE_NONE][0]['value'] = $location['pcode'];
      $term->field_location[LANGUAGE_NONE][0]['wkt'] = $location['wkt'];
      if (isset($location['parent'])) {
        $parent = humanitarianresponse_locations_load_by_pcode($location['parent']);
        $term->parent = $parent->tid;
      }
      taxonomy_term_save($term);
    }
  }
}

/**
 * Alter mapping targets for entities. Use this hook to add additional target
 * options to the mapping form of Node processors.
 *
 * If the key in $targets[] does not correspond to the actual key on the node
 * object ($node->key), real_target MUST be specified. See mappers/link.inc
 *
 * For an example implementation, see mappers/content.inc
 *
 * @param &$targets
 *   Array containing the targets to be offered to the user. Add to this array
 *   to expose additional options. Remove from this array to suppress options.
 *   Remove with caution.
 * @param $entity_type
 *   The entity type of the target, for instance a 'node' entity.
 * @param $bundle_name
 *   The bundle name for which to alter targets.
 */
function humanitarianresponse_locations_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  if ($entity_type == 'taxonomy_term' && $bundle_name == 'locations') {
    $targets['my_node_field'] = array(
      'name' => t('My custom node field'),
      'description' => t('Description of what my custom node field does.'),
    );
  }
}
